print('Enter the name of cat 1:')
catName1 = input()
print('Enter the name of cat 1:')
catName2 = input()
print('Enter the name of cat 1:')
catName3 = input()
print('Enter the name of cat 1:')
catName4 = input()
print('Enter the name of cat 1:')
catName5 = input()
print('Enter the name of cat 1:')
catName6 = input()
print('The cat names are:')
print(catName1 + ' ' + catName2 + ' ' + catName3 + ' ' + catName4 + ' ' + catName5 + ' ' + catName6 )

